cf:
  api: api.run.pivotal.io
  username: changeme
  password: changeme
  organization: NY
  space: corbs
  domain: cfapps.io
  skipSslValidation: true
jars:
  folder: /Users/corbett/Desktop/shop/jars

