cf:
  api: api.sys.retro.io
  username: changeme
  password: changeme
  organization: retro
  space: arcade
  domain: apps.retro.io
  skipSslValidation: true
jars:
  folder: /Users/corbett/Desktop/shop/jars

