jars:
  folder: /Users/corbs/dev/github/todos-apps/jars
cf:
  api: api.sys.retro.io
  username: corbs
  password: changeme
  organization: retro
  space: arcade
  domain: apps.retro.io
  skipSslValidation: true
